### ISSUE TITLE
Heroku "POST" returns nil

### ISSUE THREAD

**Issue by rmaes4** [gtchance/FirebaseSwift#10]
So I'm developing a server side swift web application using Vapor. Everything was running great on my local machine until I decided to push to heroku. After some debugging I've narrowed down my issue to the following code:

```swift
guard let response = DatabaseHelper.firebase.post(path: getDB(), value: data) else {
````

On my local machine it returns and all is well. On heroku it is returning nil. The data is getting pushed to the database however. What's going on?

**Comment by rmaes4** [comment]
Same thing with PUT. DELETE works fine

**Comment by gtchance** [comment]
@rmaes4 Does `GET` work?

**Comment by rmaes4** [comment]
Yes

**Comment by gtchance** [comment]
Are you getting any errors in your logs?

**Comment by rmaes4** [comment]
No just that it is returning nil

**Comment by rmaes4** [comment]
I can try to setup a default vapor project and add your api and push it to Heroku to try and eleminate any potential conflicts.

**Comment by gtchance** [comment]
I added more error logging in 1.6.1. See if you get anymore info from it. In the future I will add the ability to handle errors better.

**Comment by rmaes4** [comment]
The exact same code that worked for me before no longer works for me on the latest version. I am getting "unauthorized request".

**Comment by rmaes4** [comment]
You changed "Auth" to "Access token" ?

**Comment by rmaes4** [comment]
Nevermind I figured it out. Pushing to heroku right now. Will post back with results.

**Comment by rmaes4** [comment]
Well the problem is still happening. No errors it's just returning nil. This is on a blank vapor project. I might test this with another swift framework to determine if the problem is the framework or heroku. This is really strange.

**Comment by gtchance** [comment]
I assume you're using [kylef/heroku-buildpack-swift](https://github.com/kylef/heroku-buildpack-swift) and the default Heroku stack (Ubuntu 16.04)?

**Comment by rmaes4** [comment]
-----> Swift app detected
Cloning into 'swiftenv'...
Swift 3 Heroku Installer
🔢  Version: 3.1.1
🖥  Operating System: ubuntu1404
📦 Installing Swiftenv

**Comment by rmaes4** [comment]
Downloading https://swift.org/builds/swift-3.1.1-release/ubuntu1604/swift-3.1.1-RELEASE/swift-3.1.1-RELEASE-ubuntu16.04.tar.gz
/tmp/swiftenv-3.1.1- /tmp/build_cf3241973cb05f0e29c44a12a4e36639

**Comment by gtchance** [comment]
I'm not sure if this would cause the problem you're having, but the Swift build you're downloading doesn't match the operating system you're running on. The build is for 16.04 and the os is 14.04.

**Comment by rmaes4** [comment]
Hmm. not sure how I would go about changing that. This is all so odd to me. I just want my app to work in production :(

**Comment by rmaes4** [comment]
Going to test with the Perfect framework/buildpack.

**Comment by gtchance** [comment]
In your Heroku app go to settings. Under info you'll see stack. Upgrade it to heroku-16.

**Comment by rmaes4** [comment]
It actually shows heroku-16 and this build pack: https://github.com/vapor-community/heroku-buildpack

**Comment by rmaes4** [comment]
never knew running perfect on heroku was such a pain in the ass. have to figure out this makefile. give me a minute.

**Comment by rmaes4** [comment]
Couldn't figure out perfect. Attempting to run vapor on an ubuntu digital ocean droplet.

**Comment by rmaes4** [comment]
Got the same error. So we can deduce that the problem isn't Heroku. I guess it could be vapor? I need to try a different swift framework I suppose.

**Comment by rmaes4** [comment]
I was going to try to make a barebones swift file using your code and run it on DO but I can't figure out how to link it properly. I'm really pulling my hair out here. Not sure how to proceed.

**Comment by rmaes4** [comment]
Ok I think we're getting somewhere. So I created the following main.swift No vapor or anything, just pure swift.

```swift
            let baseURL = "https://example.com/"
            let secret = "XXX"
            let firebase = Firebase(baseURL: baseURL, accessToken: nil)
            firebase.auth = secret
            let result = firebase.post(path: "test", value: [
                "test1": "test",
                "test2": "test"
            ])
            print(result)
```
And I am still getting nil. Again though, the push operation is working. This to me means that the problem is that the code works on Mac but not on linux. I hope that helps. As to why that is I couldn't tell you.

Running:

    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.3 LTS
    Release:	16.04
    Codename:	xenial

**Comment by gtchance** [comment]
I'll do some testing on Ubuntu.

**Comment by rmaes4** [comment]
Thank you. Let me know if I can help in any way.

**Comment by gtchance** [comment]
Turns out the built in JSON deserialization tool can have trouble on linux. Try out the updated 1.6.2 release.

**Comment by vzsg** [comment]
Pardon me, I'm just here because the Vapor heroku-buildpack was mentioned, but what do you think of running the unit tests on Linux too? I noticed that both FirebaseSwift and Just are tested on Travis under macOS only.

While I don't have good experiences with Travis + their sudo-enabled Linux image, CircleCI 2.0 is super easy to hook up for Swift.

**Comment by rmaes4** [comment]
It seems to still be broken :(

**Comment by gtchance** [comment]
@rmaes4 Fixed! Once the json deserialization was fixed, there was still a type casting fail on linux. All my unit tests passed on Ubuntu 16.04. Update to FirebaseSwift 1.6.3.

**Comment by vzsg** [comment]
You don't really need SwiftyJSON anymore. 😉

**Comment by gtchance** [comment]
I do need it. The built in JSONSerialization was failing to parse the response at all.

**Comment by vzsg** [comment]
Not really. The AnyObject casts caused the `nil`s, not to mention that SwiftyJSON is [just a direct wrapper on top of JSONSerialization](https://github.com/SwiftyJSON/SwiftyJSON/blob/master/Source/SwiftyJSON.swift#L106) too.

**Comment by rmaes4** [comment]
It works! Thank you so much.

**Comment by gtchance** [comment]
@vzsg The try-catch with JSONSerialization was failing. The initial problem had nothing to do with casting.

**Comment by vzsg** [comment]
I really don't understand, as this works for me too:

```
    /// Converts an HTTPResult to json
    ///
    /// - Returns: A json object
    func contentAsJSONMap() -> Any? {
        guard let data = content else {
            return nil
        }

        return try? JSONSerialization.jsonObject(with: data, options: [])
    }
```

But I'll shut up now. 👍

**Comment by gtchance** [comment]
What OS and swift version are you using? I appreciate your input. I’d love to get rid of SwiftyJSON but i want to make sure I don’t break it for anyone.

**Comment by gtchance** [comment]
On Swift 3.1.1 and Ubuntu 16.04 your code fails for me. However, this works for me: ```try JSONSerialization.jsonObject(with: data, options: opt)```

**Comment by vzsg** [comment]
Try running the project multiple times. I think there is a threading issue in Just, which causes invalid data to be returned in sometimes. On Swift 4, this is even more apparent (even with 1.6.3!), as the worker thread crashes with a memory deallocation error regularly.

---

I'm testing on Ubuntu 16.04 in Docker. I tested with the swift:latest (which has Swift 3.1.1) and swiftdocker/swift:latest (4.0) images and get this nondeterministic behavior.

BTW, if you check the linked source of SwiftyJSON, you'll see that it really doesn't make a difference. Neither does `try?` vs `try`.

**Comment by gtchance** [comment]
@rmaes4 `.allowFragments` is what makes it work for me.

**Comment by gtchance** [comment]
@rmaes4 When are you experiencing problems with Just? Both Async and Synchronous calls?

**Comment by rmaes4** [comment]
@gtchance I think youre looking for @vzsg

**Comment by vzsg** [comment]
I was only testing the synchronous POST method.

**Comment by gtchance** [comment]
@vzsg Thanks for the input on everything. I removed SwiftyJSON as a dependency. I wasn't able to reproduce your threading issues, but I haven't yet tested with Swift 4 on Ubuntu.
