### ISSUE TITLE
NSURLConnection HTTP load failed

### ISSUE THREAD

**Issue by justinshuls** [gtchance/FirebaseSwift#11]
Getting the following inconstantly, on a GET request, using 1.5.0:
[] nw_coretls_read_one_record tls_handshake_process: [-9802]
NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9802)

**Comment by gtchance** [comment]
@justinshuls What are you running it on? Also, try updating to the latest version. You can still use the deprecated auth method.

**Comment by justinshuls** [comment]
Will do, but having trouble updating the project. Using perfect assistant the URL: https://github.com/gtchance/FirebaseSwift.git causes a "not valid SPM"

**Comment by justinshuls** [comment]
/.build/checkouts/FirebaseSwift.git--8640578754916314878 remote update -p
error: cyclic dependency declaration found:

**Comment by gtchance** [comment]
I was able to get 1.6.4 to work with Perfect Assistant by first running `swift build` manually
