### ISSUE TITLE
var

### ISSUE THREAD

**Issue by davinese** [gtchance/FirebaseSwift#13]
Hey, whenever I plug in a string variable into get, it doesn't work. It just doesn't do anything. It used to work before I updated it.  Can you help me out. 

for example:
var usercode: String!

func doSomething() {
usercode = johnappleseed123

let user = firebase.get("user" + usercode)
}

**Comment by gtchance** [comment]
Make sure you are performing `GET` on the correct path. If the user ID is `usercode`, then the path should be `"user/" + usercode`.

**Comment by davinese** [comment]
it works now. Thanks!
