### ISSUE TITLE
Getting no version error when adding with Perfect Assistant

### ISSUE THREAD

**Issue by justinshuls** [gtchance/FirebaseSwift#3]
"Warning: This package has no versions" and will not integrate.

**Comment by gtchance** [comment]
Try now. I removed the "v" from the tag.

**Comment by davinese** [comment]
hey gtchance, I tried to put the value into a label, put it always turns into nil. can you help me out 

    @IBAction func retrieveValue() {
        firebase.get(path: "user/john_id/middleInitial") { user in
            
            self.retrievedValue.setText(user as? String)
            
        }
    }
