### ISSUE TITLE
GET doesn't work for me

### ISSUE THREAD

**Issue by davinese** [gtchance/FirebaseSwift#4]
I tried to put the value into a label, but it turns into nil. can you help me out

@IBAction func retrieveValue() {
    firebase.get(path: "user/john_id/middleInitial") { user in
        
        self.retrievedValue.setText(user as? String)
        
    }
}

... and also.. how do I generate keys like childByAutoID?

**Comment by davinese** [comment]
the value turns into nil

**Comment by gtchance** [comment]
@davinese The first problem you described was a bug. You can either update to version 1.5.0 (just released) or instead do ```firebase.get(path: "user/john_id")``` then access `middleInitial` in the resulting dictionary. Obviously I recommend the former.
`childyAutoID` is created when posting. The result of the post will be `["name": "childByAutoID"]`.
e.g. 
```
let newUser = [
  "name": "John",
  "email": "john@example.com"
]
// sync
let result = firebase.post(path: "user", value: newUser)
print(result) // ["name": "john_id"]
```
