### ISSUE TITLE
Firebase Auth

### ISSUE THREAD

**Issue by davinese** [gtchance/FirebaseSwift#5]
This isn't really an issue, but how do you sign in and create accounts?

**Comment by gtchance** [comment]
To interact with your database, all you need to do is set the auth token for the Firebase object: 
```
let firebase = Firebase(baseURL: "https://myapp.firebaseio.com/", auth: "mytoken")
```
There is not currently support for creating user accounts. You might want to look into using the Firebase REST API directly: https://firebase.google.com/docs/reference/rest/auth/
