### ISSUE TITLE
Auth token

### ISSUE THREAD

**Issue by rmaes4** [gtchance/FirebaseSwift#7]
How do I generate the auth token?

**Comment by gtchance** [comment]
@rmaes4 You can use your database secret as an auth token.

**Comment by gtchance** [comment]
I'm going to do some research on updating the current authentication method. https://firebase.google.com/docs/database/rest/auth

**Comment by rmaes4** [comment]
@gtchance Ok yeah I think that is deprecated now. Please let me know what you find out.

**Comment by gtchance** [comment]
@rmaes4 1.6.0 now uses the Google OAuth2 access tokens. See [here](https://firebase.google.com/docs/database/rest/auth) on how to create one.

**Comment by rmaes4** [comment]
Is there a way to do that using swift?

**Comment by gtchance** [comment]
You can use this [Objective-C library](https://github.com/google/google-api-objectivec-client-for-rest/). Otherwise, you can just use the example code [here](https://firebase.google.com/docs/database/rest/auth) to create a token then use it in your Swift code. If you find a way to do this all in Swift, let me know.

**Comment by rmaes4** [comment]
So I'm using Vapor which is a server side swift framework. I found [this](https://github.com/vapor/jwt) but I can't seem to wrap my head around how all of this oauth stuff works. I tried looking up the implementation in the Google java client library code but it seemed to be hidden.

**Comment by rmaes4** [comment]
https://stackoverflow.com/questions/46396224/how-do-i-generate-an-auth-token-using-jwt-for-google-firebase

Hoping I can get some help

**Comment by justinshuls** [comment]
@rmaes4 might be a Vapor python module like Perfect Python, than you can to run:

```
import google.auth.transport.requests
import requests
from google.oauth2 import service_account
from google.auth.transport.requests import AuthorizedSession

scopes = [
  "https://www.googleapis.com/auth/userinfo.email",
  "https://www.googleapis.com/auth/firebase.database"
]

credentials = service_account.Credentials.from_service_account_file("KEY FILE PATH", scopes=scopes)


request = google.auth.transport.requests.Request()
credentials.refresh(request)
access_token = credentials.token
print access_token

```

**Comment by davidseek** [comment]
I dont understand why this is closed since it is not answered. i'm running into the same issue.
able to perform the requests with the deprecated way, but not able to create a token in swift with vapor.
any news?
